### ISSUE TITLE
Rest API Question

### ISSUE THREAD

**Issue by arthurvanl** [mvdgeijn/pax8#3]
Hallo,

Ik zag dat je een handige koppeling had gemaakt voor de pax8 api. 
Ik loop alleen tegen een probleem aan waar subscription products niet in de products list zit. Als ik de specifieke product op haal (via id) kom ik het product wel tegen. Enig idee hoe dit kan?

**Comment by mvdgeijn** [comment]
Hou er rekening mee dat het per maximaal 100 regels (zo uit mijn hoofd) gaat. Dus je zal meerdere keren een aanroep moeten doen.
